# Generated by Django 2.0.7 on 2019-08-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='abcd', max_length=20),
            preserve_default=False,
        ),
    ]
