# Generated by Django 2.0.7 on 2019-08-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_password1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
